default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: 
  
development:
  <<: *default
  database: legal_diary_development

test:
  <<: *default
  database: legal_diary_test

production:
  <<: *default
  database: legal_diary_production
